# 公有仓库
source 'https://github.com/CocoaPods/Specs.git'
## 私有仓库
# source 'https://git.nya.pics/Ligo/LigoPods.git'

use_frameworks!

target 'PYAsyncOperation_Example' do
  pod 'PYAsyncOperation', :path => '../'

  target 'PYAsyncOperation_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
